### ISSUE TITLE
working with DBF::Table in parallel processes

### ISSUE THREAD

**Issue by drssdinblck** [infused/dbf#86]
To speed up some imports from a legacy FoxPro DB into a postgresql, I am trying to utilize the parallel gem. But whenever I pass an array of DBF::Record objects to the parallel worker processes, I get the following error:

```
TypeError (no _dump_data is defined for class StringIO):
/usr/local/bundle/gems/parallel-1.12.1/lib/parallel.rb:66:in `dump'
/usr/local/bundle/gems/parallel-1.12.1/lib/parallel.rb:66:in `work'
/usr/local/bundle/gems/parallel-1.12.1/lib/parallel.rb:382:in `block (4 levels) in work_in_processes'
/usr/local/bundle/gems/parallel-1.12.1/lib/parallel.rb:495:in `with_instrumentation'
/usr/local/bundle/gems/parallel-1.12.1/lib/parallel.rb:381:in `block (3 levels) in work_in_processes'
/usr/local/bundle/gems/parallel-1.12.1/lib/parallel.rb:369:in `loop'
/usr/local/bundle/gems/parallel-1.12.1/lib/parallel.rb:369:in `block (2 levels) in work_in_processes'
/usr/local/bundle/gems/parallel-1.12.1/lib/parallel.rb:206:in `block (2 levels) in in_threads'
```

Now I know this is not due to your gem, but the problem lies that the parallel gem is relying on `Marshal.dump`, but `Marshal.dump` does not work together with StringIO, which is the underlying class of DBF::Record data. 

Do you have any suggestions how to make it work together?

This is the code I try to execute:
```ruby
slices = dbf_table.each_slice(1023).to_a
def import_in_parallel(slices)
  Parallel.each(
    -> { slices.pop || Parallel::Stop},
    in_processes: [1, Concurrent.processor_count - 1].max
  ) do |slice|
    perform_import_job(slice)
  end
end
```

**Comment by drssdinblck** [comment]
Nevermind, my approach just wasn't good. Instead of passing the table slice by slice (which I thought would save memory in the processes to be forked) I went with passing the slice index. Also looks much cleaner now.

```ruby
def import_in_parallel(table)
  processes = [1, Parallel.processor_count - 2].max

  Parallel.each(table.each_slice(slice_size), in_processes: processes) do |slice|
    perform_import_job(slice)
  end
end
```

Anyway, thanks for the effort you put into this gem :-)
