### ISSUE TITLE
CLI tool clean exit on EPIPE

### ISSUE THREAD

**Issue by SheetJSDev** [infused/dbf#93]
using ruby 2.6.3p62 on osx, running a command like `dbf -c test.dbf | head -n 1` prints the desired result but also dumps the following error message:

```
Traceback (most recent call last):
	11: from /usr/local/bin/dbf:23:in `<main>'
	10: from /usr/local/bin/dbf:23:in `load'
	 9: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.3/bin/dbf:55:in `<top (required)>'
	 8: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.3/lib/dbf/table.rb:200:in `to_csv'
	 7: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.3/lib/dbf/table.rb:116:in `each'
	 6: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.3/lib/dbf/table.rb:116:in `times'
	 5: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.3/lib/dbf/table.rb:116:in `block in each'
	 4: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.3/lib/dbf/table.rb:200:in `block in to_csv'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/csv.rb:1186:in `<<'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/csv/writer.rb:44:in `<<'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/csv/writer.rb:44:in `<<'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/csv/writer.rb:44:in `write': Broken pipe @ io_write - <STDOUT> (Errno::EPIPE)
```

Is there a way to make the CLI tool respond to EPIPE errors on exit cleanly in this case?  It may suffice to add the line

```ruby
Signal.trap('PIPE','SYSTEM_DEFAULT');
```

near the top of the `bin/dbf` script

**Comment by infused** [comment]
I added the Signal.trap, so give it a try now with version 4.1.5.

I did try to replicate the error using ruby 2.6.3p62 on MacOS (using RVM),
but it worked fine for me.

**Comment by SheetJSDev** [comment]
4.1.5 resolved the issue, thank you very much!
