### ISSUE TITLE
column name cannot be empty (DBF::Column::NameError)

### ISSUE THREAD

**Issue by SheetJSDev** [infused/dbf#95]
dbf 4.1.6 throwing errors on files from Visual dBASE 7:

```
$ dbf -s Fish.dbf 

Database: Fish.dbf
Type: (8c) 
Memo File: true
Records: 10

Fields:
Name             Type       Length     Decimal
------------------------------------------------------------------------------
Traceback (most recent call last):
	11: from /usr/local/bin/dbf:23:in `<main>'
	10: from /usr/local/bin/dbf:23:in `load'
	 9: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.6/bin/dbf:50:in `<top (required)>'
	 8: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.6/lib/dbf/table.rb:110:in `columns'
	 7: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.6/lib/dbf/table.rb:215:in `build_columns'
	 6: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.6/lib/dbf/table.rb:306:in `safe_seek'
	 5: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.6/lib/dbf/table.rb:217:in `block in build_columns'
	 4: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.6/lib/dbf/table.rb:217:in `tap'
	 3: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.6/lib/dbf/table.rb:225:in `block (2 levels) in build_columns'
	 2: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.6/lib/dbf/table.rb:225:in `new'
	 1: from /Library/Ruby/Gems/2.6.0/gems/dbf-4.1.6/lib/dbf/column.rb:46:in `initialize'
/Library/Ruby/Gems/2.6.0/gems/dbf-4.1.6/lib/dbf/column.rb:116:in `validate_name': column name cannot be empty (DBF::Column::NameError)
```

[Fish.dbf.zip](https://github.com/infused/dbf/files/7018765/Fish.dbf.zip)

**Comment by infused** [comment]
I've added support for this file type (8c) in version 4.2.0. Let me know if you run into any issues. 

Thanks,
Keith
